version: "3.8"

services:
  mongodb:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rsstag_admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password
      MONGO_INITDB_DATABASE: rss
    volumes:
      - ./mongo-data:/for_dumps
      - ./mongo-init:/docker-entrypoint-initdb.d

  rsstag:
    depends_on:
      - mongodb
    links:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8885:8885"
    restart: always
    volumes:
      - ./rsscloud.conf:/rsstag/rsscloud.conf
      - ./input_files:/input_files
